# ---------------------------------------------------------------------------
# WINDOW RULES — tối ưu riêng cho bộ ứng dụng gaming + dev (theo StealNateOS)
# ---------------------------------------------------------------------------
windowrulev2 = float, class:^(pavucontrol)$
windowrulev2 = float, class:^(nm-connection-editor)$
windowrulev2 = float, class:^(blueman-manager)$
windowrulev2 = float, title:^(Picture-in-Picture)$
windowrulev2 = pin, title:^(Picture-in-Picture)$
windowrulev2 = size 800 500, title:^(Picture-in-Picture)$
windowrulev2 = move 100%-820 100%-520, title:^(Picture-in-Picture)$

# game fullscreen — tắt hẳn animation/blur để không mất fps
windowrulev2 = immediate, class:^(cs2)$
windowrulev2 = immediate, class:^(steam_app_.*)$
windowrulev2 = noanim, class:^(cs2)$
windowrulev2 = fullscreen, class:^(cs2)$

windowrulev2 = opacity 0.95 0.90, class:^(kitty)$
windowrulev2 = opacity 0.97 0.92, class:^(code)$

windowrulev2 = workspace 2, class:^(zen-browser)$
windowrulev2 = workspace 3, class:^(code)$

# hyprlock / OSD không bị blur/dim theo layer khác
layerrule = blur, waybar
layerrule = ignorezero, waybar
layerrule = blur, rofi
layerrule = ignorezero, rofi
layerrule = blur, wlogout
layerrule = blur, swayosd
